### ISSUE TITLE
outofmemory error

### ISSUE THREAD

**Issue by wagam** [HandiPressante/HandiPressante-android#1]
log au moment d'ouverture de la fiche :
l'application ne plante pas forcément

java.lang.OutOfMemoryError: Failed to allocate a 5760012 byte allocation with 3039588 free bytes and 2MB until OOM

**Comment by Nico-lb** [comment]
Problème corrigé lors du commit 81eee93 en plaçant toutes les images HD dans le répertoire approprié (_drawable-xhdpi_).
